### ISSUE TITLE
Localstack pro migration and setup environment workflow

### ISSUE THREAD

**Issue by mahinuzzaman** [CraftsmenLtd/BloodConnect#118]
For the Bloodconnect project, we need to add CI/CD pipelines to support deployments to **stage** and **prod** environments.

Another issue was with localstack. As we are using localstack extensively, we have decided to go with **LocalStack Pro**  version. We already have an account setup for this and we need to update our ci/cd pipeline accordingly.

Finally, we need to automatically clean up resources when branches are deleted or merged.

### Acceptance Criteria:
- [x] **LocalStack Pro Integration**:  Add LocalStack Pro access in the GitHub CI workflow.
   
- [ ] **Stage and Prod Environment Configuration**:  
   - Set up GitHub deployment workflows for **stage** and **prod** environments.
   - Ensure environment-specific configurations for stage and prod (e.g., credentials, subdomains, resource prefixes).
   
- [ ] **Commit Hash Storage and Cleanup**:  
   - Store the latest deployment commit hash for each branch.
   - Automatically trigger resource cleanup (destroy branch) when a branch is deleted or a pull request is merged, using the stored commit hash.
   
- [ ] **Documentation**:  Document the steps and process for the **stage** and **prod** environments.

**Comment by mahinuzzaman** [comment]
Is there gonna be permission for prod deployment access? or anyone can deploy it.

**Comment by KhirulIslam** [comment]
@mahinuzzaman is this ticket open or closed ? i am confused

**Comment by mahinuzzaman** [comment]
forgot to move to the review column. updated
