### ISSUE TITLE
Create coding guideline document

### ISSUE THREAD

**Issue by shuaibq3** [CraftsmenLtd/BloodConnect#15]

**Comment by dorjoycr** [comment]
Noticed this ticket. Just wanted to say when the coding guidelines are documented, we should mention that all the code files should contain the following lines ideally at the top of the source files as a comment block like this:
```
// Copyright 2023 Craftsmen Ltd
// SPDX-License-Identifier: Apache-2.0
```

**Comment by shuaibq3** [comment]
> Noticed this ticket. Just wanted to say when the coding guidelines are documented, we should mention that all the code files should contain the following lines ideally at the top of the source files as a comment block like this:
> 
> ```
> // Copyright 2023 Craftsmen Ltd
> // SPDX-License-Identifier: Apache-2.0
> ```

is this needed to put the file contents under the  mentioned license? or having the LICENSE.md cover all the files in the repo?

**Comment by dorjoycr** [comment]
> is this needed to put the file contents under the mentioned license? or having the LICENSE.md cover all the files in the repo?

I think from the repo standpoint the LICENSE does cover all the files but when someone from outside will try to re-use our code say some files s/he will automatically get the copyright on the files as well. It's more like a recommended practice other open source projects follow so it makes sense to try to follow that.
