### ISSUE TITLE
Donation request compilation step

### ISSUE THREAD

**Issue by KhirulIslam** [CraftsmenLtd/BloodConnect#155]
This part is a prerequisite before searching for donors. In this step we calculate the total number of donors to be notified to fulfill this request. We check the total number of donors we will notify to satisfy the request. We also calculate the gohash for the donation centre that later gets used for donor search step later. We can increase the number of donors to be notified based on urgency level. 

We can divide the process into three steps. They are : 
1. Calculating the number of bags required. 
2. Calculate donor counts to be notified. 
3. Calculate geohash of the donation centre. 

**Proposed Solution:**
We can do these with two lamnda functions and a step function step. **Calculating the number of bags required** includes quarrying dynamo to check how many donors we have found so far and adjust the calculation accordingly. We can do this via lambda. If it's possible to do it without a lambda, that's even better. 

**Calculate donor counts to be notified.**  can be a step function step that calculate number of donors we will be notified at this time. This need bit more context that is explained in the context section. 

**Calculate geohash of the donation centre.** is a lambda that will give us a geohash and we will need it while quering dynamodb 

**Additional Context:**
Here we are discussing **Calculate donor counts to be notified.** With an example,

 The donation request contains a few parameters. User-defined parameters are : 

1. Blood group  2. Donation center.  3. Donation date time  4. Number of bags 5. Urgency

In this step, we calculate the total number of donors we need to notify. Based on the urgency level and total time spent on the current donor search, our number of donors required to be notified can increase.. Let's go through an example.

Urgency level: 2

number of bags: 5

minimum donors: 2

TOTAL NUMBER OF DONORS TO BE NOTIFIED  :  Urgency level * number of bags * minimum donors = 2 * 5 * 2 = 20

Also, this step calculates the delay period, the amount of time our system will wait to retry searching for donors again. 

The output of the step: 

1. total number of donors to be notified.  2. donation center's gohash 

## Solution breakdown.
- [ ] Calculating blood bag requirement with unit test coverage.
- [ ] Geohash calculation with unit test coverage and calculation of donors to be notified. 

## Acceptance Criteria

- [ ] Calculate donor count to be notified for both new requests or if the request has been routed through the retry step
- [ ] Geohash calculation

## Additional Notes (optional)
Check [here](https://drive.google.com/file/d/1ya9swGl5iBPYcSVBcL0NmUqBUIE5DHvI/view?usp=sharing) for detailed design

**Comment by mahinuzzaman** [comment]
story points 5

**Comment by EbrahimAli-RU** [comment]
Story Point 4

**Comment by Shahed-Chy-Suzan** [comment]
story points 5-6

**Comment by Biplob14** [comment]
SP 6
