### ISSUE TITLE
List missing things and questions for first release

### ISSUE THREAD

**Issue by mahinuzzaman** [CraftsmenLtd/BloodConnect#234]
- [ ] If we build the APK in `preview` mode, the app's APK throws an error during authentication. This issue needs to be resolved. - moved
- [ ] geohash R&D - moved
- [x] if user changes for same device. Device registration gets error. Need to fix it - done
- [ ] Cancel request post - moved
- [ ] donor can cancel accepted request - moved
- [x] authorization error on get request when using domain - done
- [ ] save last login time - moved
- [ ] image upload and cdn setup - moved
- [ ] do we need option to hide phone number. If yes how would someone communicate if phone hidden - moved
- [ ] bulk notification. Ebrahim vai knows - moved
- [ ] from multiple phone numbers, set a primary phone number - moved
- [ ] gsi is missing for user profile entry and user model - done
- [ ] mail on forgot password - need to check
- [ ] phone number missing on sso login - moved
- [ ] for the very first time with google login shown an error message, but if the we go back then works perfectly - moved
- [ ] search on city dropdown - moved
- [ ] donor distance from preferred location to hospital - moved
- [ ] notify donor 1 hour before donation - moved
- [ ] age, weight and height are private info. can we show something else? - moved
- [ ] set primary phone number - moved
- [ ] Better way of returning response. (string/json) - moved
- [ ] notification page ( in UI) - moved

### **Shuaib vai**
- search algorithm adjustment - moved
- height weight helper text  - moved
- dob based validation for donation eligibility  - moved
- terms of service and privacy policy links   - moved
- "no donations found" text change  - moved
- text boxes multiline adjustable  - moved
- show ignored requests to donor   - moved
- search in city field   - moved
- accept loader  - moved
- text adjustment in demo  - moved
- My activity: no space in text  - moved
- Donation center and preferred area distance text hint  - moved
- Frequent reminders before certain time to donors  - moved
- Save data locally  - moved
- profile and profile up  - moved

**Comment by Biplob14** [comment]
As we don't have chat feature yet. If any donors accept any blood request, he doesn't have any other option without calling to seekers phone number. 
What if seeker press No on the following state? what should we do for now?
![image](https://github.com/user-attachments/assets/6cfc2fe8-e391-40cf-a7b7-be29a093b95a)
