### ISSUE TITLE
create Account Screen on Mobile Application

### ISSUE THREAD

**Issue by Biplob14** [CraftsmenLtd/BloodConnect#244]
## Feature Request
Create the Account screen for mobile application

## Acceptance Criteria

- [ ] Show basic user data part
- [ ] Create two separate section with data shown on UI
- [ ] Navigate through bottom navigation to this page

## UI screenshot

![Image](https://github.com/user-attachments/assets/ec795695-9e74-4a5a-8b5d-80105d3b2820)

**Comment by mahinuzzaman** [comment]
duplicate ticket #245 
need to close this
