### ISSUE TITLE
Create `user` service

### ISSUE THREAD

**Issue by shuaibq3** [CraftsmenLtd/BloodConnect#34]
A micro-service in the `core/services` directory that will facilitate user related workflows through http endpoints. Example workflows include:
  - Mobile number OTP and email login
  - SSO related workflows for login: google, facebook, whatsapp
  - receive roles based on which permissible actions across the system can be determined
  - get relevant user information, including settings, role

**Comment by KhirulIslam** [comment]
Covered in stories under epic-1 #62
