### ISSUE TITLE
Dockerized Dev Environment

### ISSUE THREAD

**Issue by melon-ruet** [CraftsmenLtd/BloodConnect#51]
As a developer
Given I have BloodConnect project
And I want to install and run my dev environment
When I need to install and run easily
Then I want to use docker for all of my dependencies

### Task
1. Create a Dockerfile with a bare minimum debian image
2. Add all dependencies in that Dockerfile (terraform, npm, nodejs, sphinx, graphviz and CI/CD dependencies)
3. Makefile commands for terraform format, terraform plan, terraform deploy, npm lint, npm test, npm install dependencies
4. Add documentasion with all commands and a page for dockerized dev environment

### Acceptance Criteria
1. Commands must be run in local machine in any OS which supports docker
2. Commands must be reusable with CI
3. Necessary documentaion

**Comment by KhirulIslam** [comment]
@melon-ruet looks like this is done, closing the ticket
