### ISSUE TITLE
Run the project locally

### ISSUE THREAD

**Issue by shuaibq3** [CraftsmenLtd/BloodConnect#57]
Developer documentation to run the project locally. Review the [Setup the Project](https://craftsmenltd.github.io/BloodConnect/development/GettingStarted.html) page in the developer docs and assess if it is sufficient to implement this. If needed, that page can be edited and modified with a new PR. If that page seems to have everything we need, put in a comment with your observation in this issue to initiate a discussion.

- Should include step by step instruction in details, starting from cloning the repository, to running in local environment.
- Should include the commands to be executed, where applicable.
- Should keep `OS` specific scenario in mind.
- Should include `env` dependencies, if applicable.

**Comment by KhirulIslam** [comment]
closing this ticket as this is a duplicate to #58

**Comment by melon-ruet** [comment]
Reopened as this is not duplicate of #58

**Comment by melon-ruet** [comment]
Seems this is closed with proper documentation.
