### ISSUE TITLE
E-01-S02 Domain registration

### ISSUE THREAD

**Issue by KhirulIslam** [CraftsmenLtd/BloodConnect#74]
We need a new Domain for bloodconnect and have it registered in route53. As it's an opensource project, it should be `.org` domain. It can be bought from AWS or any other 3rd party services. If it's bought from somewhere else, we wanna manage it via route53. 

**Acceptance criteria:** 
1. Domain bought and configured with route53
2. HTTPS with auto reniewal.
3. Integration with a front-end application or backend API.

**Comment by Biplob14** [comment]
From our stand-up discussion I came to know that the has been purchased and set to route53. I am planning to go forward with another parts of these task.
