### ISSUE TITLE
E-01-S006 User registration and login using mobile application

### ISSUE THREAD

**Issue by KhirulIslam** [CraftsmenLtd/BloodConnect#78]
As an mobile app user, i should be able to signup and login to the application. User registration using mobile app will need the following data. 

- Name *
- Email *
- Mobile number *

**Acceptance criteria :** 

1. Blueprint for mobile app.
2. Successful app user registration with mobile/email varification based on user preferance. 
3. Successful login into the app using username and password.

**Comment by EbrahimAli-RU** [comment]
[Mobile App Ticket](https://github.com/orgs/CraftsmenLtd/projects/7/views/1?filterQuery=create+mobi&pane=issue&itemId=80465775)
