### ISSUE TITLE
Create commit template

### ISSUE THREAD

**Issue by shuaibq3** [CraftsmenLtd/BloodConnect#8]
Add commit template to ensure that each commit contains the issue number as prefix. The agreed upon format for commit message is `I#${issue_number} ${commit_message}`.

**Comment by SayefReyadh** [comment]
@shuaibq3 vai,
The `I#${issue_number} ${commit_message}` followed convention is unable to tag the issue itself, how about `I-#${issue_number} ${commit_message}` ? Any thoughts?
