### ISSUE TITLE
E03 S02 Doner notify mechanism

### ISSUE THREAD

**Issue by KhirulIslam** [CraftsmenLtd/BloodConnect#84]
As an app-user, I can request donation-request once I find a donor. Upon donation-request, a notification should be sent to the prospective donor. The notification message should include the following information. 

- Required blood type. 
- Location. 
- Time and Date. 
- Severity level. (emergency or others).
- Personalized message. (300 characters)

**Acceptance criteria:** 
1. Multiple donation-request of upto 20 at a time.
2. Notification History. 
3. Basic structure for a notification system that can be used for other types if notification if needed in the future.

**Comment by mahinuzzaman** [comment]
story points 3
not sure. don't know how notification will be implemented

**Comment by Shahed-Chy-Suzan** [comment]
story points 6

**Comment by EbrahimAli-RU** [comment]
Story point 5
