### ISSUE TITLE
E03 S03 Doner confirmation.

### ISSUE THREAD

**Issue by KhirulIslam** [CraftsmenLtd/BloodConnect#85]
Once Donors are notified, a Donor can accept the request. Upon accepting request there will be a record of donors request acceptance against the blood request post.

**Acceptance criteria:**
1. check if request is request post is valid
3. If the previously notified owner tries to accept an already accepted donor, they will see messages saying the request is complete.
4. Donor confirmation History.

**Comment by mahinuzzaman** [comment]
story points 5

**Comment by Shahed-Chy-Suzan** [comment]
story points 7

**Comment by EbrahimAli-RU** [comment]
Story point 6.

**Comment by Biplob14** [comment]
SP 6
