### ISSUE TITLE
Sphinx documentation does not run

### ISSUE THREAD

**Issue by sakibstark11** [CraftsmenLtd/BloodConnect#93]
## Bug Report

**Describe the bug:**
When I try to run `make sphinx-html` it throws error where the docker container doesn't even boot up.
**Severity:**

- [x] P0 (Critical)
- [ ] P1 (High Priority)
- [ ] P2 (Medium Priority)
- [ ] P3 (Low Priority)

## Impact (optional)

Describe the impact of the bug or feature being addressed, based on the bug reporter's judgment or your own assessment.

**Steps to Reproduce:**
Outline the steps to reproduce the bug. Provide a list of actions that led to the bug occurring.

**Screenshots/Code Snippets:**
If applicable, add screenshots or code snippets to help explain the problem.

**Additional Context:**
Add any other context about the problem here, such as relevant logs, error messages, or any troubleshooting steps you have already taken.

## Reproducible Demo (optional)

If possible, provide a link to a minimal, reproducible demo of the bug. This can be a GitHub repository, a CodePen, or any other publicly accessible code example that demonstrates the issue.

## Impact Analysis (optional)

If you have considered the potential impact or severity of this bug on the system or users, please provide an analysis here. This could include any specific areas affected or potential risks associated with the bug.

## Possible Solution (optional)

If you have any ideas or suggestions on how to fix the bug, please provide them here.

## Related Issues/PRs (optional)

If you know of any related issues or pull requests that might be helpful for understanding or fixing this bug, please list them here.

## Additional Notes (optional)

Add any additional notes or comments you think are relevant to this bug report.

**Comment by melon-ruet** [comment]
@sakibstark11 you need to run
```sh
make run-command-sphinx-html
```
